# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PYUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 511)
        self.pushButton1_1 = QtWidgets.QPushButton(Form)
        self.pushButton1_1.setGeometry(QtCore.QRect(50, 60, 181, 41))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pushButton1_2 = QtWidgets.QPushButton(Form)
        self.pushButton1_2.setGeometry(QtCore.QRect(50, 110, 181, 41))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.pushButton2_1 = QtWidgets.QPushButton(Form)
        self.pushButton2_1.setGeometry(QtCore.QRect(50, 290, 181, 41))
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.pushButton2_2 = QtWidgets.QPushButton(Form)
        self.pushButton2_2.setGeometry(QtCore.QRect(50, 360, 181, 41))
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.pushButton2_4 = QtWidgets.QPushButton(Form)
        self.pushButton2_4.setGeometry(QtCore.QRect(50, 430, 181, 41))
        self.pushButton2_4.setObjectName("pushButton2_4")
        self.pushButton3 = QtWidgets.QPushButton(Form)
        self.pushButton3.setGeometry(QtCore.QRect(390, 60, 181, 41))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(Form)
        self.pushButton4.setGeometry(QtCore.QRect(390, 170, 181, 41))
        self.pushButton4.setObjectName("pushButton4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 250, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 181, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(360, 120, 211, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(360, 250, 121, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(400, 300, 81, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(400, 330, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton2_3 = QtWidgets.QPushButton(Form)
        self.pushButton2_3.setGeometry(QtCore.QRect(400, 390, 181, 41))
        self.pushButton2_3.setObjectName("pushButton2_3")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 170, 201, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(40, 200, 211, 16))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton1_1.setText(_translate("Form", "1.1 Draw Contour"))
        self.pushButton1_2.setText(_translate("Form", "1.2 Count Coins"))
        self.pushButton2_1.setText(_translate("Form", "2.1 Find Coners"))
        self.pushButton2_2.setText(_translate("Form", "2.2 Find Intrinsic"))
        self.pushButton2_4.setText(_translate("Form", "2.4 Find Distortion"))
        self.pushButton3.setText(_translate("Form", "3.1 Augmented Reality"))
        self.pushButton4.setText(_translate("Form", "4.1 Stereo Disparity Map"))
        self.label.setText(_translate("Form", "1. Find Contour"))
        self.label_2.setText(_translate("Form", "2.Calibration"))
        self.label_3.setText(_translate("Form", "3. Augmented Reality"))
        self.label_4.setText(_translate("Form", "4 . Stereo Disparity Map"))
        self.label_5.setText(_translate("Form", "2.3 Find Extrinsic "))
        self.label_6.setText(_translate("Form", "Select image"))
        self.pushButton2_3.setText(_translate("Form", "2.3 Find Extrinsic"))
        self.label_7.setText(_translate("Form", "There are      coins in coin01.jpg"))
        self.label_8.setText(_translate("Form", "There are      coins in coin02.jpg"))
